# Generated by Django 2.2.2 on 2019-06-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('po_box', models.CharField(max_length=50, verbose_name='P.O BOX')),
                ('building', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True, verbose_name='Begin attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('adm', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='admission number')),
                ('full_name', models.CharField(max_length=50)),
                ('admission_year', models.DateField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_done', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default='', on_delete=True, to='internship.Department'),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('staff_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('PO_Box', models.CharField(max_length=50, verbose_name='P.O BOX')),
                ('branch', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Student')),
            ],
        ),
    ]
