# Generated by Django 2.2.2 on 2019-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
