# Generated by Django 2.2.2 on 2019-06-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('PO_BOX', models.CharField(blank=True, max_length=50, null=True, verbose_name='P.O BOX')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('application_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Student')),
            ],
        ),
    ]
