# Generated by Django 2.2.2 on 2019-06-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
