# Generated by Django 2.2.2 on 2019-06-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Awaiting'), ('F', 'Failed'), ('S', 'Successfull')], default='P', max_length=50),
        ),
    ]
