# Generated by Django 2.2.2 on 2019-06-27 13:57

import django.core.validators
from django.db import migrations, models
import internship.models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_auto_20190624_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), internship.models.max_value_current_year]),
        ),
    ]
