# Generated by Django 2.2.2 on 2019-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_auto_20190627_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('semester', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=0)),
            ],
        ),
    ]
