# Generated by Django 2.2.2 on 2019-06-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_academicyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
