# Generated by Django 2.2.2 on 2019-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_delete_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('semester', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=0)),
            ],
        ),
    ]
