# Generated by Django 2.2.2 on 2019-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
