# Generated by Django 2.2.2 on 2019-06-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
