# Generated by Django 2.2.2 on 2019-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_auto_20190628_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
