# Generated by Django 2.2.2 on 2019-06-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0016_auto_20190628_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedsupervisor',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.Department'),
        ),
    ]
