# Generated by Django 2.2.2 on 2019-07-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_notification_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Department'),
        ),
    ]
