# Generated by Django 2.2.2 on 2019-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_auto_20190718_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='outgoing',
            field=models.BooleanField(default=False),
        ),
    ]
