# Generated by Django 2.2.2 on 2019-08-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
