# Generated by Django 2.2.2 on 2019-08-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0025_delete_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='internship.Department')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Supervisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Student')),
            ],
        ),
    ]
